export const API_ENDPOINTS = {
  DOCUMENT_MANAGEMENT_CARDS_SAFETY_PROTOCOL: `/getDocumentsByCategory`,
  UPDATE_DOCUMENT: `/updateDocument`,
  SAFETY_TRAINING_CARD_DATA: `/getTrainingByCategory`,
  MANAGE_CATEGORIES: `/getAllCategories`,
  CREATE_MANAGE_CATEGORIES: `/createCategory`,
  SAFETY_CATEGORIES: `/getAllTrainingCategories`,
  CREATE_SAFETY_CATEGORIES: `/createTrainingCategory`,
  DELETE_SAFETY_CATEGORY: `/deleteTrainingCategory`,
  SEARCH_DATA: `/searchDocument`,
  DELETE_DOCUMENT_MANAGEMENT_DATA: `/deleteDocument`,
  DELETE_SAFETY_DATA: `/deleteTrainingDoc`,
  DELETE_MANAGE_CATEGORY: `/deleteCategory`,
  USER_MANAGEMENT_GET_ALL_STAFF: `/getAllUsers`,
  USER_MANAGEMENT_VIEW: `/getUser`,
  USER_MANAGEMENT_EDIT: `/editUser`,
  USER_MANAGEMENT_SEARCH: `/getAllUsers`,
  CREATE_QUESTIONS: `/createQues`,
  INCIDENT_REPORTING_STATS: `/getIncidentStats`,
  INCIDENT_REPORTING_TABLE_DATA: `/getIncidentApi`,
  // INCIDENT_REPORTING_SEARCH: ``,
  DASHBOARD_DOCUMENTS_DATA: `/getDocumentStats`,
  DASHBOARD_SAFETY_TRAINING_DATA: `/getTrainingStats`,
  GET_TRAINING_DOC: `/getTrainingDoc`,
  GET_DOC_Bycategory: `/getDocumentApi`,
  DOCUMENT_MANAGEMENT_TABLE_VIEW: `/getDocViews`,
  LOGIN: `/login`,
  CREATE_QUESTIONS: `/createQues`,
  CREATE_DOCUMENT: `/createDocument`,
  CREATE_TRAINING: `/saveTrainingdoc`,
  VIEW_ALLQUESTION: `/viewallQues`,
  GET_ALL_TRAINING_DOC: `/getAllTrainingDoc`,

  UPDATE_INCIDENT_REPORTING_SPECIFIC_PAGE_CHANGES: `/updateIncident`,
  LINE_CHART_INCIDENT_API: "/getIncidentsbyYear",
  LINE_CHART_USER_API: "/getUserRegistrations",
};
